name: Keep Render Instance Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # Toutes les 10 minutes
  workflow_dispatch:  # Pour pouvoir déclencher manuellement

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping to keep alive
        run: curl -s https://briefy-backend.onrender.com
        
